# Generated by Django 2.1.2 on 2018-12-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('rate_cash_buy', models.FloatField()),
                ('rate_cash_sell', models.FloatField()),
                ('rate_sight_buy', models.FloatField()),
                ('rate_sight_sell', models.FloatField()),
            ],
        ),
    ]
