# Generated by Django 2.1.2 on 2018-12-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_data', '0002_aud_cny_eur_gbp_krw_sgd_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cny',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jpy',
            name='date',
            field=models.DateField(),
        ),
    ]
