# Generated by Django 2.1.2 on 2018-12-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_data', '0003_auto_20181217_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aud',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eur',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gbp',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='krw',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sgd',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usd',
            name='date',
            field=models.DateField(),
        ),
    ]
