# Generated by Django 2.1.2 on 2018-12-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_data', '0004_auto_20181217_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KRW',
        ),
    ]
